### PR TITLE
IOS Logs update

### PR DESCRIPTION
**Pull request by jigar-f**
We recently discovered that, when reporting an issue, iOS does not include tunnel logs. Since the tunnel runs in a separate process, the log paths are different. we need to ensure that iOS zips two folders: `logs` for the app and `tunnelLogs` for the tunnel process.

### CODE REVIEW

**Comment by jigar-f** [comment]
Do let me know if I am missing anything here or if there might be some other (better way to do this) thanks!

**Comment by jay-418** [comment]
One quick side question: are these logs able to be manually retrieved like we [do for desktop](https://github.com/getlantern/customer-support/blob/main/how-to/logs.md)?

@greySkiesMarsh struggles to diagnose issues for users when the normal issue submission pipeline fails.

**Comment by jigar-f** [comment]
@jay-418, unfortunately, there’s no direct way to download app group data on iOS. There isn’t an official method to do it.

**Review by garmr-ulfr — APPROVED** [review]
LGTM

**Pull request merged**
