### PR TITLE
Implement FroPay and add plans-v4

### PR DESCRIPTION
**Pull request by jigar-f**
- Added plans-v4 endpoint
- Updated protoc file to use icons and plans on same response, avoid calling plans API.

### CODE REVIEW

**Comment by jigar-f** [comment]
Not sure why  TestPaymentMethod, But I am looking.

**Comment by jigar-f** [comment]
@reflog I found the issue why tets are failing due to they are running on staging, And API changes are not there, Are you planning to push changes on staging?

**Comment by reflog** [comment]
@jigar-f our staging server wasn't updated in years. We should really disable all code in flashlight that hits it and replace with some sort of a mock. cc @hwh33 @myleshorton

**Review by reflog — APPROVED** [review]

**Comment by jigar-f** [comment]
Thank @reflog, For now, I will keep the same later we can make changes.

**Review by reflog — APPROVED** [review]

**Pull request merged**
