### PR TITLE
Ads support for iOS

### PR DESCRIPTION
**Pull request by jigar-f**

### CODE REVIEW

**Comment by jigar-f** [comment]
@myleshorton Could you take a look at this?

**Comment by jigar-f** [comment]
If this looks good, Could you please published it so, I can test ads feature in IOS, Thanks

**Comment by myleshorton** [comment]
Sorry I'm not sure how to go about publishing it tbh

**Comment by jigar-f** [comment]
@myleshorton I think we have CI (It run on midnight) for this it will take care of it, I guess

**Comment by jigar-f** [comment]
Tagging @reflog for more info

**Comment by reflog** [comment]
@jigar-f looks ok and after merging it will be picked up by CI and deployed

**Comment by jigar-f** [comment]
@reflog @myleshorton Could you guy check CI failing, Should I go ahed and merge it still?

**Comment by myleshorton** [comment]
I think it needs a go mod tidy

**Review by reflog — APPROVED** [review]

**Comment by reflog** [comment]
I guess no longer relevant. Closing

**Pull request closed without merging**
