### PR TITLE
Add callbacks for initialization states

### PR DESCRIPTION
**Pull request by atavism**

### CODE REVIEW

**Comment by jigar-f** [comment]
@atavism Is this ready to test?

**Comment by jigar-f** [comment]
@ atavism Is this ready to test or are some changes still pending? if completed I would like to know where is a callback on a flashlight so that I can get all callbacks.

**Comment by atavism** [comment]
@jigar-f Yes, you can start testing this one (you should see the different callbacks triggered in the logs). There's a [atavism/add-init-callbacks](https://github.com/getlantern/lantern-client/tree/atavism/add-init-callbacks) lantern-client branch that's using this version of flashlight.

**Comment by atavism** [comment]
You can see how the callbacks are specified creating a new client [here](https://github.com/getlantern/lantern-client/blob/atavism/add-init-callbacks/desktop/app/app.go#L233)

**Comment by jigar-f** [comment]
Thanks, @atavism for letting me know, I just ran my [branch](https://github.com/getlantern/lantern-client/blob/d09d012c14c217bd7ee2f8f2789d63cac062ea5f/desktop/app/app.go#L231) and I am getting multiple callbacks from the same method, for ex I am getting onInit and onSucceedingProxy called multiple times, Is this suppose to happen?

**Comment by atavism** [comment]
> I just ran my [branch](https://github.com/getlantern/lantern-client/blob/d09d012c14c217bd7ee2f8f2789d63cac062ea5f/desktop/app/app.go#L231) and I am getting multiple callbacks from the same method, for ex I am getting onInit and onSucceedingProxy called multiple times, Is this suppose to happen?

Sorry, I missed your comment! It should be fine calling onSucceedingProxy(true) multiple times, but `onInit` should only be called once, whenever the client is ready/we successfully fetch the global config the first time.

I just made that change and updated flashlight on the https://github.com/getlantern/lantern-client/tree/atavism/add-init-callbacks branch if you wanna check..

```
May 13 03:24:04.739 - 0m0s DEBUG app.settings: settings.go:198 Sending Lantern settings to new client
May 13 03:24:04.739 - 0m0s DEBUG lantern-desktop.app: pro.go:202 Fetching user data again to see if any changes
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:54551/j4jZh5BDPoA=/
May 13 03:24:04.763 - 0m0s DEBUG otel: otel.go:38 Configuring OpenTelemetry with sample rate 8000 and op sample rates map[client_started:1 client_stopped:1 proxy_rank:24000 replica_metrics:1 replica_torrent_peer_sent_data:16 report_issue:1]
May 13 03:24:04.763 - 0m0s DEBUG otel: otel.go:39 Connecting to endpoint api.honeycomb.io:443
May 13 03:24:04.763 - 0m0s DEBUG fronted: direct.go:114 Vetting 10 initial candidates in series
May 13 03:24:04.763 - 0m0s DEBUG otel: otel.go:40 Using headers map[x-honeycomb-team:D7LRAYj3uCxrSb7WZjO24C]
May 13 03:24:04.763 - 0m0s DEBUG otel: key.go:116 Will report traces to OpenTelemetry
May 13 03:24:04.764 - 0m0s DEBUG lantern-desktop.app: app.go:429 onInit called...
May 13 03:24:04.764 - 0m0s DEBUG lantern-desktop.app: app.go:433 Received new config update..
May 13 03:24:04.764 - 0m0s DEBUG lantern-desktop.autoupdate: autoupdate.go:76 Software version: 9999.99.99
```

**Comment by jigar-f** [comment]
Thanks, @atavism for the update.

**Comment by jigar-f** [comment]
@atavism Lets put on hold on this one, if we merge this won't work on IOS, Since we not using a flashlight.

**Comment by jigar-f** [comment]
@reflog @hwh33  Does this look good to you? Can we merge this?

**Comment by reflog** [comment]
I'll leave this one for @hwh33

**Pull request closed without merging**
