### PR TITLE
Added Tapsell feature flag.

### PR DESCRIPTION
**Pull request by jigar-f**

### CODE REVIEW

**Comment by jigar-f** [comment]
@reflog Any idea why TestProductionGlobal is failing?

**Comment by reflog** [comment]
@jigar-f not really.
let's ping @hwh33

**Comment by jigar-f** [comment]
@hwh33 Is this okay to merge?

**Comment by hwh33** [comment]
That test failure should be resolved by https://github.com/getlantern/flashlight/pull/1414.  Could you try merging in `main` and then see whether the tests pass?

**Review by hwh33 — APPROVED** [review]
Assuming that fixes the issue, feel free to merge.  This LGTM

**Comment by jigar-f** [comment]
@hwh33 Seems like the test is still failing

**Comment by hwh33** [comment]
Heh you ran into a different test failure, which started earlier today and affected all branches.  We had a test which relied on external network dependencies.  We're working on fixing it with mock services and in the meantime have decided to just [skip it for now](https://github.com/getlantern/flashlight/pull/1419).

Anyway, the tests are passing on your branch now.  You can squash and merge this whenever you're ready!

**Pull request merged**
